### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lenovouser** [lowply/webhook#1]
I've tried a 100 different things now and I am still getting this error:

```
Error running script: /x/srv/homepage/webhook.sh
```

I have done `chmod 770` and `600`, it doesn't work. If I just type `/x/srv/homepage/webhook.sh`, the script runs perfectly fine. The **webhook** app is getting started as **root** by **supervisord**.

**Comment by lenovouser** [comment]
This seems to be unmaintained, so I am going to close this.

**Comment by lowply** [comment]
@lenovouser My apologies for not answering your issue for so long time. Once I get it fixed I will update.

**Comment by lowply** [comment]
Hi @lenovouser,

I have pushed the updated version of webhook and it is working fine in both root and normal user.

Here's my environment.

```
# cat /etc/issue
CentOS release 6.4 (Final)
Kernel \r on an \m
# go version
go version go1.6 linux/amd64
# uname -a
Linux [hostname_hidden] 2.6.32-358.18.1.el6.x86_64 #1 SMP Wed Aug 28 17:19:38 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

If it still doesn't work, I suggest running webhook with address binded to 0.0.0.0:4000 and receive GitHub's webhook payload directly. If it works, your problem would probably be related to supervisord. And you're right, `script.sh` should have permission `700`.

Here's sample config file to do that.

```
bindaddress = "0.0.0.0"
bindport    = "4000"
execfile    = "/path/to/script.sh"
logfile     = "/var/log/webhook.log"
key         = "xxxxxxxxxxxxxxxxxxx"
```

**Comment by lenovouser** [comment]
Seems to work, thanks!
